/*
Proyecto para optar a la certificación de desarrollo de bases de datos orienta-
das a objetos del Instituto Profesional Santo Tomás Talca.

Autor: Pablo Iván Bustamante Idro.
Profesor: Claudio Diaz Pacheco.

Título del proyecto: Sistema de registro de viaje de camiones.

*/

--------------------------------------------------------------------------------
-----------------------------USUARIO PROYECTO-----------------------------------

CREATE USER PROYECTO IDENTIFIED BY 12345;
GRANT CONNECT TO PROYECTO;
GRANT RESOURCE TO PROYECTO;
GRANT CREATE ANY TYPE TO PROYECTO;
GRANT UNDER ANY TYPE TO PROYECTO;
GRANT EXECUTE ANY TYPE TO PROYECTO;

--------------------------------------------------------------------------------

-----------------------------CREACION DE OBJETOS--------------------------------

CREATE OR REPLACE TYPE T_LOG AS OBJECT(
CODIGO NUMBER,
TABLA VARCHAR(15),
ACCION VARCHAR(15),
FECHASISTEMA DATE,
ESTADO NUMBER(1));
/

ALTER TYPE T_LOG ADD ATTRIBUTE USUARIO VARCHAR(50) CASCADE;
ALTER TYPE T_LOG DROP ATTRIBUTE ESTADO CASCADE;

CREATE OR REPLACE TYPE T_PERSONA AS OBJECT(
RUT VARCHAR(15),
NOMBRE VARCHAR(15),
APELLIDO VARCHAR(15),
ESTADO NUMBER(1)) NOT FINAL;
/


CREATE OR REPLACE TYPE T_CHOFER UNDER T_PERSONA(
FECHA_INGRESO DATE,
MEMBER FUNCTION FULLNAME RETURN VARCHAR,
MEMBER FUNCTION CATEGORIA RETURN VARCHAR,
MEMBER FUNCTION TOTALVIAJES RETURN NUMBER);
/

CREATE OR REPLACE TYPE T_CAMION AS OBJECT(
PATENTE VARCHAR(15),
ANO NUMBER,
DESCRIPCION VARCHAR(25),
MARCA VARCHAR(25),
ESTADO NUMBER(1),
MEMBER FUNCTION TOTALVIAJES RETURN NUMBER );
/

ALTER TYPE T_CAMION ADD ATTRIBUTE EJES NUMBER CASCADE

CREATE OR REPLACE TYPE T_UBICACION AS OBJECT(
CODIGO NUMBER,
DESCRIPCION VARCHAR(25),
ESTADO NUMBER(1));
/

CREATE OR REPLACE TYPE T_VIAJE AS OBJECT(
CODIGO NUMBER,
FECHA_INICIO DATE,
FECHA_LLEGADA DATE,
CARGA VARCHAR(100),
ORIGEN REF T_UBICACION,
DESTINO REF T_UBICACION,
CHOFER REF T_CHOFER,
CAMION REF T_CAMION,
ESTADO NUMBER(1));
/

--------------------------------------------------------------------------------
----------------------------CREACION DE TABLAS----------------------------------


CREATE TABLE CHOFER OF T_CHOFER (RUT PRIMARY KEY)
OBJECT IDENTIFIER IS PRIMARY KEY;

CREATE TABLE CAMION OF T_CAMION (PATENTE PRIMARY KEY)
OBJECT IDENTIFIER IS PRIMARY KEY;

CREATE TABLE UBICACION OF T_UBICACION (CODIGO PRIMARY KEY)
OBJECT IDENTIFIER IS PRIMARY KEY;

CREATE TABLE VIAJE OF T_VIAJE (
--	(CODIGO,CAMION,CHOFER) PRIMARY KEY,
	CODIGO PRIMARY KEY,
	SCOPE FOR (CHOFER) IS CHOFER, 
	SCOPE FOR (CAMION) IS CAMION, 
	SCOPE FOR (ORIGEN) IS UBICACION,
	SCOPE FOR (DESTINO) IS UBICACION)
OBJECT IDENTIFIER IS PRIMARY KEY;

CREATE TABLE LOG OF T_LOG;

--------------------------------------------------------------------------------
------------------------------CREACION DE BODY----------------------------------

CREATE OR REPLACE TYPE BODY T_CHOFER IS

MEMBER FUNCTION FULLNAME RETURN VARCHAR IS

	BEGIN
		RETURN SELF.NOMBRE || ' ' || SELF.APELLIDO;
	END;

MEMBER FUNCTION CATEGORIA RETURN VARCHAR IS
ANS NUMBER;
CATEGORY VARCHAR(22);
	BEGIN
		SELECT MONTHS_BETWEEN(SYSDATE,FECHA_INGRESO)/12 INTO ANS FROM CHOFER WHERE SELF.RUT=RUT;
		
		IF ANS IS NULL THEN
			CATEGORY := 'NO DATA';
		ELSIF ANS < 2 THEN
			CATEGORY := 'CHOFER NACIONAL';
		ELSIF ANS < 5 THEN
			CATEGORY := 'CHOFER INTERNACIONAL';
		ELSE
			CATEGORY := 'INSTRUCTOR';
		END IF;	
		RETURN CATEGORY;
	END;

MEMBER FUNCTION TOTALVIAJES RETURN NUMBER IS
TOTAL_VIAJES NUMBER;
	BEGIN
		SELECT COUNT(V.CODIGO) INTO TOTAL_VIAJES 
		FROM VIAJE V, CHOFER C 
		WHERE V.CHOFER.RUT=C.RUT AND C.ESTADO=1 AND V.ESTADO=1 AND C.ESTADO=1 AND SELF.RUT = C.RUT;
		
		IF TOTAL_VIAJES IS NULL THEN
			TOTAL_VIAJES := 0;
		END IF;

		RETURN TOTAL_VIAJES;
	END;

END;
/


CREATE OR REPLACE TYPE BODY T_CAMION IS

MEMBER FUNCTION TOTALVIAJES RETURN NUMBER IS
TOTAL_VIAJES NUMBER;
	BEGIN
		SELECT COUNT(V.CODIGO) INTO TOTAL_VIAJES 
		FROM VIAJE V, CAMION C 
		WHERE V.CAMION.PATENTE=C.PATENTE AND C.ESTADO=1 AND V.ESTADO=1
                AND C.PATENTE = SELF.PATENTE;
		
		IF TOTAL_VIAJES IS NULL THEN
			TOTAL_VIAJES := 0;
		END IF;

		RETURN TOTAL_VIAJES;
	END;

END;
/


