
--------------------------------------------------------------------------------
------------------------------TRIGER UBICACION----------------------------------
CREATE SEQUENCE INDEX_UBICACION
START WITH 2
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER UBICACION_TGG
BEFORE INSERT OR DELETE OR UPDATE ON UBICACION
FOR EACH ROW
BEGIN

  IF INSERTING THEN
    INSERT INTO LOG (CODIGO,TABLA, ACCION, FECHASISTEMA) VALUES (1,'UBICACION', 
    	'INSERTAR', SYSDATE);
  ELSIF DELETING THEN
  	INSERT INTO LOG (CODIGO,TABLA, ACCION, FECHASISTEMA) VALUES (1,'UBICACION', 
  		'ELIMINAR', SYSDATE);
  ELSE
  	IF :OLD.ESTADO = 1 AND :NEW.ESTADO = 0 THEN
  	INSERT INTO LOG (CODIGO,TABLA, ACCION, FECHASISTEMA) VALUES (1,'UBICACION', 
  		'DESACTIVAR', SYSDATE);

  	ELSIF :OLD.ESTADO = 0 AND :NEW.ESTADO = 1 THEN
  	INSERT INTO LOG (CODIGO,TABLA, ACCION, FECHASISTEMA) VALUES (1,'UBICACION', 
  		'REACTIVAR', SYSDATE);

  	ELSE
  	INSERT INTO LOG (CODIGO,TABLA, ACCION, FECHASISTEMA) VALUES (1,'UBICACION', 
  		'ACTUALIZAR', SYSDATE);
  	END IF;
    
  END IF;

SELECT INDEX_UBICACION.NEXTVAL 
INTO :NEW.CODIGO FROM DUAL;
END;
/


--------------------------------------------------------------------------------
------------------------------TRIGGER VIAJE-------------------------------------

CREATE SEQUENCE INDEX_CODIGO
START WITH 2
INCREMENT BY 1;



CREATE OR REPLACE TRIGGER VIAJE_TGG
BEFORE INSERT OR DELETE OR UPDATE ON VIAJE
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    INSERT INTO LOG (CODIGO,TABLA, ACCION, FECHASISTEMA) VALUES (1,'VIAJE', 
    	'INSERTAR', SYSDATE);
  ELSIF DELETING THEN
  	INSERT INTO LOG (CODIGO,TABLA, ACCION, FECHASISTEMA) VALUES (1,'VIAJE', 
  		'ELIMINAR', SYSDATE);
  ELSE
  	IF :OLD.ESTADO = 1 AND :NEW.ESTADO = 0 THEN
  	INSERT INTO LOG (CODIGO,TABLA, ACCION, FECHASISTEMA) VALUES (1,'VIAJE', 
  		'DESACTIVAR', SYSDATE);

  	ELSIF :OLD.ESTADO = 0 AND :NEW.ESTADO = 1 THEN
  	INSERT INTO LOG (CODIGO,TABLA, ACCION, FECHASISTEMA) VALUES (1,'VIAJE', 
  		'REACTIVAR', SYSDATE);

  	ELSE
  	INSERT INTO LOG (CODIGO,TABLA, ACCION, FECHASISTEMA) VALUES (1,'VIAJE', 
  		'ACTUALIZAR', SYSDATE);
  	END IF;
    
  END IF;

SELECT INDEX_CODIGO.NEXTVAL 
INTO :NEW.CODIGO FROM DUAL;
END;
/



--------------------------------------------------------------------------------
--------------------------------TRIGGER CHOFER----------------------------------




CREATE OR REPLACE TRIGGER CHOFER_TGG
  BEFORE INSERT OR DELETE OR UPDATE ON CHOFER
  FOR EACH ROW
BEGIN
  IF INSERTING THEN
    INSERT INTO LOG (CODIGO,TABLA, ACCION, FECHASISTEMA) VALUES (1,'CHOFER', 
    	'INSERTAR', SYSDATE);
  ELSIF DELETING THEN
  	INSERT INTO LOG (CODIGO,TABLA, ACCION, FECHASISTEMA) VALUES (1,'CHOFER', 
  		'ELIMINAR', SYSDATE);
  ELSE
  	IF :OLD.ESTADO = 1 AND :NEW.ESTADO = 0 THEN
  	INSERT INTO LOG (CODIGO,TABLA, ACCION, FECHASISTEMA) VALUES (1,'CHOFER', 
  		'DESACTIVAR', SYSDATE);

  	ELSIF :OLD.ESTADO = 0 AND :NEW.ESTADO = 1 THEN
  	INSERT INTO LOG (CODIGO,TABLA, ACCION, FECHASISTEMA) VALUES (1,'CHOFER', 
  		'REACTIVAR', SYSDATE);

  	ELSE
  	INSERT INTO LOG (CODIGO,TABLA, ACCION, FECHASISTEMA) VALUES (1,'CHOFER', 
  		'ACTUALIZAR', SYSDATE);
  	END IF;
    
  END IF;
END;
/




--------------------------------------------------------------------------------
------------------------------TRIGGER CAMION------------------------------------

CREATE OR REPLACE TRIGGER CAMION_TGG
  BEFORE INSERT OR DELETE OR UPDATE ON CAMION
  FOR EACH ROW
BEGIN
  IF INSERTING THEN
    INSERT INTO LOG (CODIGO,TABLA, ACCION, FECHASISTEMA) VALUES (1,'CAMION', 
    	'INSERTAR', SYSDATE);
  ELSIF DELETING THEN
  	INSERT INTO LOG (CODIGO,TABLA, ACCION, FECHASISTEMA) VALUES (1,'CAMION', 
  		'ELIMINAR', SYSDATE);
  ELSE
  	IF :OLD.ESTADO = 1 AND :NEW.ESTADO = 0 THEN
  	INSERT INTO LOG (CODIGO,TABLA, ACCION, FECHASISTEMA) VALUES (1,'CAMION', 
  		'DESACTIVAR', SYSDATE);

  	ELSIF :OLD.ESTADO = 0 AND :NEW.ESTADO = 1 THEN
  	INSERT INTO LOG (CODIGO,TABLA, ACCION, FECHASISTEMA) VALUES (1,'CAMION', 
  		'REACTIVAR', SYSDATE);

  	ELSE
  	INSERT INTO LOG (CODIGO,TABLA, ACCION, FECHASISTEMA) VALUES (1,'CAMION', 
  		'ACTUALIZAR', SYSDATE);
  	END IF;
    
  END IF;
END;
/

--------------------------------------------------------------------------------
--------------------------TRIGGER CODIGO LOG------------------------------------

CREATE SEQUENCE INDEX_LOG
START WITH 1
INCREMENT BY 1;


CREATE OR REPLACE TRIGGER LOG_TGG
BEFORE INSERT ON LOG
FOR EACH ROW
BEGIN
SELECT INDEX_LOG.NEXTVAL 
INTO :NEW.CODIGO FROM DUAL;
END;
/


